name: A workflow for SEM coursework Group 20
on:
  push:
    branches:
      - master
      - develop
      - feature/integration_testing
jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Unit Tests
        run: mvn -Dtest=com.napier.sem.DatabaseTest test


  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Integration Tests and CodeCov
        run: |
          docker build -t database ./db 
          docker run --name world -dp 33060:3306 database
          mvn -Dtest=com.napier.sem.IntegrationTest test          
          docker stop world
          docker rm world
          docker image rm database
      - name: CodeCov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # now required for public repos too
          directory: ./target/site/jacoco
          flags: Integration Tests # optional
          verbose: true # optional (default = false)
          slug: sim-macdonald/SEM-Coursework

  build:
    name: Build Run in Docker and Deploy Release
    runs-on: ubuntu-latest
    needs:
      - extract-branch
      - check-folders
      - unit-test
      - integration-test

    # Only run this job if the src/main/ or src/test/ folders have been modified. Also skip this job if the branch is "develop".
    if: ${{ needs.check-folders.outputs.run_build_job == 'true' && needs.extract-branch.outputs.branch != 'develop' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Skip testing in this command, as we already ran the tests in the previous jobs.
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true

      - name: Run docker Compose
        run: docker-compose up --abort-on-container-exit
